"""Fast CPython C-API helpers for typed hot paths (dict, str, bytes, …).

Re-exports compiled Cython helpers from ``picop.cy*`` submodules. Prefer
:mod:`picop.hot` for micro-opt starters; full surface stays on ``picop`` /
``picop.cy*``. Soft Strategy B aliases were removed in 0.3 — see
``picop.compat.COMPAT_MAP`` / ``__getattr__`` migration hints.
"""

from __future__ import annotations

from .__about__ import __version__
from .cyansi import (
    ansi_bg8,
    ansi_bold,
    ansi_fg8,
    ansi_fg256,
    ansi_reset,
    ansi_strip,
    ansi_wrap,
)
from .cyarray import (
    array_check,
    array_check_exact,
    array_clone,
    array_copy,
    array_eq,
    array_ne,
    array_extend,
    array_len,
    array_resize,
    array_resize_smart,
    array_zero,
)
from .cybool import (
    bool_check,
    bool_eq,
    bool_from_long,
    bool_true,
    bool_false,
)
from .cycomplex import (
    complex_check,
    complex_check_exact,
    complex_eq,
    complex_from_doubles,
    complex_real_as_double,
    complex_imag_as_double,
)
from .cynumber import (
    num_abs,
    num_add,
    num_and,
    num_as_ssize,
    num_check,
    num_eq,
    num_divmod,
    num_float,
    num_floordiv,
    num_index,
    num_index_check,
    num_inplace_add,
    num_inplace_and,
    num_inplace_floordiv,
    num_inplace_lshift,
    num_inplace_matmul,
    num_inplace_mod,
    num_inplace_mul,
    num_inplace_or,
    num_inplace_pow,
    num_inplace_rshift,
    num_inplace_sub,
    num_inplace_truediv,
    num_inplace_xor,
    num_invert,
    num_long,
    num_lshift,
    num_matmul,
    num_mod,
    num_mul,
    num_neg,
    num_or,
    num_pos,
    num_pow,
    num_rshift,
    num_sub,
    num_truediv,
    num_xor,
)
from .cyobject import (
    obj_hasattr,
    obj_hasattr_cstr,
    obj_getattr,
    obj_getattr_cstr,
    obj_setattr,
    obj_setattr_cstr,
    obj_delattr,
    obj_delattr_cstr,
    obj_richcompare,
    obj_richcompare_bool,
    obj_eq,
    obj_repr,
    obj_str,
    obj_bytes,
    obj_isinstance,
    obj_issubclass,
    obj_callable,
    obj_call,
    obj_call_object,
    obj_hash,
    obj_istrue,
    obj_not,
    obj_type,
    obj_len,
    obj_size,
    obj_length_hint,
    obj_getitem,
    obj_setitem,
    obj_delitem,
    obj_as_fd,
    obj_dir,
    obj_iter,
    obj_format,
)
from .cytype import (
    type_check,
    type_check_exact,
    type_eq,
    type_is_subtype,
)
from .cyfunction import (
    func_check,
    func_eq,
    func_new,
    func_get_code,
    func_get_globals,
    func_get_module,
    func_get_defaults,
    func_set_defaults,
    func_get_closure,
    func_set_closure,
)
from .cymethod import (
    method_check,
    method_eq,
    method_new,
    method_get_function,
    method_get_self,
)
from .cymodule import (
    mod_check,
    mod_check_exact,
    mod_eq,
    mod_new,
    mod_new_object,
    mod_get_name,
    mod_get_filename,
    mod_add_object_ref,
    mod_add_int,
    mod_add_cstr,
    mod_import,
    mod_import_object,
    mod_reload,
    mod_magic_number,
)
from .cyiterator import (
    iter_check,
    iter_eq,
    iter_next,
)
from .cyiterobject import (
    seqiter_check,
    seqiter_new,
    calliter_check,
    calliter_new,
)
from .cygenobject import (
    gen_check,
    gen_check_exact,
    gen_eq,
)
from .cycellobject import (
    cell_check,
    cell_eq,
    cell_new,
    cell_get,
    cell_set,
)
from .cydescr import descr_is_data
from .cycodecs import (
    codec_register,
    codec_known,
    codec_encode,
    codec_decode,
    codec_encoder,
    codec_decoder,
    codec_incremental_encoder,
    codec_incremental_decoder,
    codec_stream_reader,
    codec_stream_writer,
    codec_register_error,
    codec_lookup_error,
    codec_strict_errors,
    codec_ignore_errors,
    codec_replace_errors,
    codec_xmlcharrefreplace_errors,
    codec_backslashreplace_errors,
    codec_namereplace_errors,
)
from .cydatetime import (
    dt_date_check,
    dt_date_check_exact,
    dt_date_eq,
    dt_datetime_check,
    dt_datetime_check_exact,
    dt_datetime_eq,
    dt_time_check,
    dt_time_check_exact,
    dt_time_eq,
    dt_timedelta_check,
    dt_timedelta_check_exact,
    dt_timedelta_eq,
    dt_date_new,
    dt_time_new,
    dt_datetime_new,
    dt_timedelta_new,
    dt_date_year,
    dt_date_month,
    dt_date_day,
    dt_datetime_year,
    dt_datetime_month,
    dt_datetime_day,
    dt_datetime_hour,
    dt_datetime_minute,
    dt_datetime_second,
    dt_datetime_microsecond,
    dt_time_hour,
    dt_time_minute,
    dt_time_second,
    dt_time_microsecond,
    dt_timedelta_days,
    dt_timedelta_seconds,
    dt_timedelta_microseconds,
)
from .cycontextvars import (
    context_eq,
    ctx_check_exact,
    ctxvar_check_exact,
    ctxtoken_check_exact,
    ctx_new,
    ctx_copy,
    ctx_copy_current,
    ctx_enter,
    ctx_exit,
    ctxvar_new,
    ctxvar_set,
    ctxvar_reset,
)
from .cymapping import (
    map_check,
    map_eq,
    map_len,
    map_has_key,
    map_has_key_cstr,
    map_del,
    map_del_cstr,
    map_keys,
    map_values,
    map_items,
    map_getitem_cstr,
    map_setitem_cstr,
)
from .cyfileobject import (
    file_from_fd,
    file_getline,
    file_write_object,
    file_write_cstr,
)
from .cypycapsule import (
    capsule_check_exact,
    capsule_eq,
    capsule_is_valid,
)
from .cyweakref import (
    weakref_check,
    weakref_check_ref,
    weakref_check_proxy,
    weakref_eq,
    weakref_new_ref,
    weakref_new_proxy,
    weakref_get_object,
)
from .cyconversion import (
    conv_cstr_to_double,
    conv_stricmp,
    conv_strnicmp,
)
from .cytime import (
    time_wall,
    time_monotonic,
    time_perf_counter,
)
from .cymarshal import (
    marshal_dumps,
    marshal_loads,
)
from .cybuffer import (
    buf_check,
    buf_copy_data,
    buf_eq,
)
from .cybytearray import (
    bytearray_check,
    bytearray_check_exact,
    bytearray_concat,
    bytearray_eq,
    bytearray_ne,
    bytearray_contains,
    bytearray_from_object,
    bytearray_len,
    bytearray_resize,
    bytearray_size,
)
from .cybytes import (
    bytes_check,
    bytes_check_exact,
    bytes_contains,
    bytes_bytearray_eq,
    bytes_eq,
    bytes_ne,
    bytes_startswith,
    bytes_endswith,
    bytes_from_object,
    bytes_len,
    bytes_size,
)
from .cydeque import (
    deque_eq,
)
from .cydict import (
    dict_check,
    dict_check_exact,
    dict_clear,
    dict_contains,
    dict_copy,
    dict_del,
    dict_get,
    dict_get_ref,
    dict_get_with_error,
    dict_len,
    dict_eq,
    dict_merge,
    dict_merge_from_seq2,
    dict_new,
    dict_pop,
    dict_proxy,
    dict_set,
    dict_setdefault,
    dict_setdefault_ref,
    dict_size,
    dict_update,
)
from .cyfloat import (
    float_as_double,
    float_check,
    float_check_exact,
    float_eq,
    float_from_double,
    float_from_cstr,
)
from .cygc import (
    gc_collect,
    gc_disable,
    gc_enable,
    gc_is_enabled,
)
from .cymemoryview import (
    memoryview_check,
    memoryview_eq,
    memoryview_ne,
    memoryview_from_object,
    memoryview_get_contiguous,
)
from .cylong import (
    long_check,
    long_check_exact,
    long_eq,
    int_eq,
    long_from_long,
    long_from_ulong,
    long_from_ssize,
    long_from_size,
    long_from_longlong,
    long_from_ulonglong,
    long_from_double,
    long_as_long,
    long_as_long_overflow,
    long_as_ssize,
    long_as_ulong,
    long_as_longlong,
    long_as_ulonglong,
    long_as_ulong_mask,
    long_as_ulonglong_mask,
    long_as_double,
)
from .cylist import (
    list_as_tuple,
    list_append,
    list_check,
    list_check_exact,
    list_clear,
    list_copy,
    list_empty,
    list_extend,
    list_get,
    list_get_checked,
    list_get_ref,
    list_insert,
    list_eq,
    list_len,
    list_reverse,
    list_set_item,
    list_set_slice,
    list_size,
    list_slice,
    list_sort,
)
from .cysequence import (
    seq_check,
    seq_size,
    seq_len,
    seq_concat,
    seq_repeat,
    seq_inplace_concat,
    seq_inplace_repeat,
    seq_get,
    seq_slice,
    seq_set,
    seq_del,
    seq_eq,
    seq_set_slice,
    seq_del_slice,
    seq_count,
    seq_contains,
    seq_index,
    seq_list,
    seq_tuple,
)
from .cyrange import (
    range_eq,
)
from .cyset import (
    set_add,
    set_any_check,
    set_any_check_exact,
    set_check,
    set_check_exact,
    set_clear,
    set_contains,
    set_copy,
    set_discard,
    set_empty,
    frozenset_check,
    frozenset_check_exact,
    frozenset_empty,
    frozenset_eq,
    frozenset_new,
    set_len,
    set_eq,
    set_new,
    set_pop,
    set_size,
    set_update,
)
from .cyslice import (
    slice_check,
    slice_eq,
    slice_new,
    slice_indices_ex,
    slice_unpack,
)
from .cystr import (
    str_all_alnum_ascii,
    str_all_alpha_ascii,
    str_all_digits,
    str_as_or_empty,
    str_char_at,
    str_concat,
    str_concat3,
    str_concat4,
    str_contains,
    str_endswith,
    str_first_char,
    str_is,
    str_is_blank,
    str_is_empty,
    str_is_not,
    str_check_exact,
    str_last_char,
    str_none_to_empty,
    str_not_empty,
    str_startswith,
    str_eq,
    str_cmp,
    str_lt,
    str_le,
    str_gt,
    str_ge,
    str_ne,
    str_or_empty,
    str_or_none,
    str_len,
    str_check,
)
from .cytuple import (
    tuple_check,
    tuple_check_exact,
    tuple_get,
    tuple_get_checked,
    tuple_eq,
    tuple_len,
    tuple_pack2,
    tuple_pack3,
    tuple_pack4,
    tuple_size,
    tuple_slice,
)
from .cyunicode import (
    uintern,
    unicode_eq,
    uutf8_bytes,
)
from .uuid import UUID, uuid4, uuid4_bytes


def __getattr__(name: str):
    """Raise with migration hint for removed Strategy B soft aliases."""
    from .compat import soft_alias_removal_hint

    hint = soft_alias_removal_hint(name)
    if hint is not None:
        raise AttributeError(hint)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__: tuple[str, ...] = (
    # Core-curated star-import surface (preferred names). Frozen at 1.0.
    # Soft aliases removed in 0.3.
    "__version__",
    "UUID",
    "uuid4",
    "uuid4_bytes",
    "dict_check",
    "dict_check_exact",
    "deque_eq",
    "range_eq",
    "dict_get",
    "dict_get_ref",
    "dict_contains",
    "dict_len",
    "dict_eq",
    "dict_size",
    "dict_set",
    "dict_del",
    "dict_pop",
    "dict_setdefault",
    "dict_update",
    "dict_clear",
    "dict_copy",
    "dict_new",
    "list_check",
    "list_check_exact",
    "list_eq",
    "list_len",
    "list_size",
    "list_get",
    "list_get_checked",
    "list_get_ref",
    "list_append",
    "list_insert",
    "list_extend",
    "list_clear",
    "set_check",
    "set_check_exact",
    "set_contains",
    "set_add",
    "set_discard",
    "set_clear",
    "set_update",
    "set_eq",
    "frozenset_eq",
    "tuple_check",
    "tuple_check_exact",
    "tuple_eq",
    "tuple_len",
    "tuple_size",
    "tuple_get",
    "tuple_get_checked",
    "tuple_pack2",
    "tuple_pack3",
    "tuple_pack4",
    "bytes_check",
    "bytes_check_exact",
    "bytes_len",
    "bytes_size",
    "bytes_contains",
    "bytes_bytearray_eq",
    "bytes_eq",
    "bytes_ne",
    "bytes_startswith",
    "bytes_endswith",
    "bytearray_check",
    "bytearray_check_exact",
    "bytearray_len",
    "bytearray_eq",
    "bytearray_ne",
    "bytearray_contains",
    "str_len",
    "str_eq",
    "str_cmp",
    "str_lt",
    "str_le",
    "str_gt",
    "str_ge",
    "str_contains",
    "str_startswith",
    "str_endswith",
    "uintern",
    "uutf8_bytes",
    "unicode_eq",
    "ansi_wrap",
    "ansi_fg8",
    "ansi_bg8",
    "ansi_strip",
    "ansi_bold",
    "ansi_reset",
    "gc_collect",
    "gc_is_enabled",
    "gc_enable",
    "gc_disable",
    "array_check",
    "array_len",
    "array_eq",
    "array_ne",
    "array_clone",
    "array_zero",
    "memoryview_check",
    "memoryview_eq",
    "memoryview_ne",
    "memoryview_from_object",
    "buf_check",
    "buf_eq",
    "slice_check",
    "slice_eq",
    "slice_new",
    "bool_check",
    "bool_eq",
    "bool_from_long",
)
