#!/usr/bin/env python3
"""Generate Tier B inventory harnesses for public ``*_eq`` helpers.

Idempotent. Run from repo root::

    python3.14 bench/tier_b/_gen_eq_inventory.py
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent

# Groups: stem -> (extra_cimports, list of helpers)
# Each helper: (name, cimport_module, ctype_or_None)
# ctype None => object args + ``tb_obj(a,k) == b`` baseline.

CONTAINERS: list[tuple[str, str, str | None]] = [
    ("list_eq", "cypy.cylist", "list"),
    ("tuple_eq", "cypy.cytuple", "tuple"),
    ("seq_eq", "cypy.cysequence", None),
    ("dict_eq", "cypy.cydict", "dict"),
    ("set_eq", "cypy.cyset", "set"),
    ("frozenset_eq", "cypy.cyset", "frozenset"),
    ("map_eq", "cypy.cymapping", None),
    ("deque_eq", "cypy.cydeque", None),
    ("range_eq", "cypy.cyrange", None),
]

BUFFERS: list[tuple[str, str, str | None]] = [
    ("bytes_eq", "cypy.cybytes", "bytes"),
    ("bytes_bytearray_eq", "cypy.cybytes", None),
    ("bytearray_eq", "cypy.cybytearray", "bytearray"),
    ("array_eq", "cypy.cyarray", "array"),
    ("memoryview_eq", "cypy.cymemoryview", "memoryview"),
    ("buf_eq", "cypy.cybuffer", None),
    ("str_eq", "cypy.cystr", "str"),
    ("unicode_eq", "cypy.cyunicode", "str"),
]

SCALARS: list[tuple[str, str, str | None]] = [
    ("bool_eq", "cypy.cybool", None),
    ("float_eq", "cypy.cyfloat", None),
    ("long_eq", "cypy.cylong", None),
    ("int_eq", "cypy.cylong", None),
    ("complex_eq", "cypy.cycomplex", None),
    ("num_eq", "cypy.cynumber", None),
    ("slice_eq", "cypy.cyslice", "slice"),
    ("dt_date_eq", "cypy.cydatetime", None),
    ("dt_time_eq", "cypy.cydatetime", None),
    ("dt_datetime_eq", "cypy.cydatetime", None),
    ("dt_timedelta_eq", "cypy.cydatetime", None),
]

MISC: list[tuple[str, str, str | None]] = [
    ("type_eq", "cypy.cytype", None),
    ("cell_eq", "cypy.cycellobject", None),
    ("obj_eq", "cypy.cyobject", None),
    ("func_eq", "cypy.cyfunction", None),
    ("method_eq", "cypy.cymethod", None),
    ("mod_eq", "cypy.cymodule", None),
    ("gen_eq", "cypy.cygenobject", None),
    ("iter_eq", "cypy.cyiterator", None),
    ("capsule_eq", "cypy.cypycapsule", None),
    ("weakref_eq", "cypy.cyweakref", None),
    ("context_eq", "cypy.cycontextvars", None),
]


def _cimports(helpers: list[tuple[str, str, str | None]]) -> str:
    by_mod: dict[str, list[str]] = {}
    for name, mod, _ in helpers:
        by_mod.setdefault(mod, []).append(name)
    lines: list[str] = []
    for mod, names in by_mod.items():
        lines.append(f"from {mod} cimport {', '.join(names)}")
    return "\n".join(lines)


def _pair(name: str, ctype: str | None) -> str:
    if ctype is None:
        return f'''
cpdef bint baseline_{name}(object a, object b, Py_ssize_t n):
    cdef Py_ssize_t k
    cdef bint r = False
    for k in range(n):
        r = tb_obj(a, k) == b
        tb_sink_bint(r)
    return r

cpdef bint cypy_{name}(object a, object b, Py_ssize_t n):
    cdef Py_ssize_t k
    cdef bint r = False
    for k in range(n):
        r = {name}(tb_obj(a, k), b)
        tb_sink_bint(r)
    return r
'''
    # typed: cast left operand; compare to typed right
    return f'''
cpdef bint baseline_{name}({ctype} a, {ctype} b, Py_ssize_t n):
    cdef Py_ssize_t k
    cdef bint r = False
    for k in range(n):
        r = <{ctype}>tb_obj(a, k) == b
        tb_sink_bint(r)
    return r

cpdef bint cypy_{name}({ctype} a, {ctype} b, Py_ssize_t n):
    cdef Py_ssize_t k
    cdef bint r = False
    for k in range(n):
        r = {name}(<{ctype}>tb_obj(a, k), b)
        tb_sink_bint(r)
    return r
'''


def write_pyx(stem: str, helpers: list[tuple[str, str, str | None]], preamble: str = "") -> None:
    parts = [
        "# cython: language_level=3, boundscheck=False, wraparound=False, initializedcheck=False",
        "# Auto-generated by _gen_eq_inventory.py — do not hand-edit.",
        _cimports(helpers),
    ]
    if preamble:
        parts.append(preamble)
    parts.append('include "_sink.pxi"')
    parts.append("")
    for name, _, ctype in helpers:
        parts.append(_pair(name, ctype).rstrip())
        parts.append("")
    (HERE / f"{stem}_tb.pyx").write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {stem}_tb.pyx ({len(helpers)} helpers)")


def main() -> None:
    write_pyx("cyeq_containers", CONTAINERS)
    write_pyx(
        "cyeq_buffers",
        BUFFERS,
        preamble="from cpython.array cimport array",
    )
    write_pyx(
        "cyeq_scalars",
        SCALARS,
        preamble=(
            "from cpython.datetime cimport import_datetime\n"
            "\n"
            "import_datetime()"
        ),
    )
    write_pyx("cyeq_misc", MISC)
    print("done — drivers are hand-maintained: cyeq_inventory.py")


if __name__ == "__main__":
    main()
